CREATE TABLE IMAGES (
	ID INT(10) UNSIGNED,
	URL VARCHAR(1000),	
    ONN VARCHAR(1000) NULL,
    OBRA INT(10) UNSIGNED,
	PRIMARY KEY (ID)  USING BTREE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE OBRA (
	ID INT(10) UNSIGNED,
	titolpag VARCHAR(1000),	
    titolmenu VARCHAR(1000),
    tipusObra VARCHAR(1000),    
	PRIMARY KEY (ID)  USING BTREE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE NOTICIES (
	ID INT(10) UNSIGNED,
	URL VARCHAR(1000),	
    nomca VARCHAR(1000),
    nomes VARCHAR(1000),
    nomen VARCHAR(1000),   
    OBRA INT(10) UNSIGNED,
	PRIMARY KEY (ID)  USING BTREE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE PDF (
	ID INT(10) UNSIGNED,
	nompdf VARCHAR(1000),	
    nomca VARCHAR(1000),
    nomes VARCHAR(1000),
    nomen VARCHAR(1000),
    data VARCHAR(1000),   
    OBRA INT(10) UNSIGNED,
	PRIMARY KEY (ID)  USING BTREE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE VISITAS (
	idVisitas INT(10) UNSIGNED,
	VISITA_DATE DATE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;